[build]
  functions = "functions"
  command = "npm run build"

[dev]
  functions = "functions"
  port = 8888         # Netlify Dev server
  targetPort = 3000   # Your React app (npm start runs on 3000)
